### ISSUE TITLE
NPE for swing app with processing

### ISSUE THREAD

**Issue by yetrr** [leaningtech/cheerpj-meta#100]
```
CheerpJ is initializing

java.lang.NullPointerException
	at java.awt.Component$FlipBufferStrategy.getDrawGraphics(Unknown Source) 
        at processing.awt.PSurfaceAWT.render(Unknown Source)
        at processing.awt.PSurfaceAWT$SmoothCanvas.paint(Unknown Source)
        at sun.awt.RepaintArea.paintComponent(Unknown Source)
        at sun.awt.RepaintArea.paint(Unknown Source)
        at com.leaningtech.cheerpj.CheerpJComponentPeer.handleEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

```
<!doctype html>
<html>
<head>
    <title>some title</title>
    <script src="https://cjrtnc.leaningtech.com/2.1/loader.js" crossorigin="anonymous"></script>
</head>
<body></body>
<script>
      cheerpjInit();
      cheerpjCreateDisplay(innerWidth, innerHeight);
      cheerpjRunJar("application.jar");
</script>
</html>
```
Jar file: https://github.com/yetrr/TicTacToe/releases/tag/1.0

**Comment by alexp-sssup** [comment]
This application requires AWT double buffering, which is not currently supported.
