### ISSUE TITLE
back/forwards mouse buttons cause applet to crash

### ISSUE THREAD

**Issue by robert245** [leaningtech/cheerpj-meta#190]
Description
I have a Logitech G502 mouse, which has side buttons usually mapped to go back/ go forwards).  There have been times I've accidentally clicked these buttons while interacting with a cheerpj applet, and it causes an unchecked exception to kill the current thread.

This can be reproduced in the official cheerpj demos, which I'll describe below

**Steps to reproduce** 
(assuming you have a mouse with forwards/back buttons)
1. Go to applet (e.g https://labs.leaningtech.com/cheerpj3/tutorials/applet#the-result) and wait for applet to load
2. Use mouse-back button

Expectation
* Mouse-back action is ignored

Actual:
* Applet stops responding to actions (cannot click most buttons)
* Stack trace emitted to console
{code}
Exception in thread "Thread-2" 
java.lang.IllegalArgumentException: button doesn't exist 0
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.RuntimeException.<init>(Unknown Source)
	at java.lang.IllegalArgumentException.<init>(Unknown Source)
	at java.awt.event.InputEvent.getMaskForButton(Unknown Source)
	at com.leaningtech.cheerpj.MouseState.sendMouseEvent(Unknown Source)
	at com.leaningtech.cheerpj.CheerpJDisplay.sendMouseEvent(Unknown Source)
	at com.leaningtech.cheerpj.CheerpJToolkit$1.run(Unknown Source)
{code}

**Comment by alexp-sssup** [comment]
Thanks for the reporting this, the problem should be fixed with the following build: https://cjrtnc.leaningtech.com/3_20240228_437/cj3loader.js
