### ISSUE TITLE
Error when using Cheerpj with Saxon

### ISSUE THREAD

**Issue by adamretter** [leaningtech/cheerpj-meta#4]
I am trying to see if I can get Cheerpj to work for the Saxon-HE XSLT processor. I was able to recompile the Jar to a .jar.js and upload it to my webserver. However when I try and use Saxon I get an error from Cheerpj like this on the console in Chrome:

```
Reporting error: Unhandled exception N4java4lang20NullPointerException/TypeError: d.v0 is not a function
    at _c4pbQ3qZcqeYCallHelpdG1a_ISGIwKHKN2c9BCo3cGKetrqSoAqYahjS3m (https://cheerpjdeploy.leaningtech.com/runtime/rt.jar.com.js:2950:2130)
    at _c4pbQ3qZcqK0CallHelper6createEt0_c8pmAqYahfSytLy0e (https://cheerpjdeploy.leaningtech.com/runtime/rt.jar.com.js:2950:3020)
    at Object.func (https://cheerpjdeploy.leaningtech.com/loader.js:468:16)
    at runContinuationStack (https://cheerpjdeploy.leaningtech.com/loader.js:287:10)
    at cheerpjSchedule (https://cheerpjdeploy.leaningtech.com/loader.js:709:4)
    at HTMLScriptElement.classLoadComplete (https://cheerpjdeploy.leaningtech.com/loader.js:177:3)
loader.js:1605

Unhandled exception N4java4lang20NullPointerException/TypeError: d.v0 is not a function
    at _c4pbQ3qZcqeYCallHelpdG1a_ISGIwKHKN2c9BCo3cGKetrqSoAqYahjS3m (https://cheerpjdeploy.leaningtech.com/runtime/rt.jar.com.js:2950:2130)
    at _c4pbQ3qZcqK0CallHelper6createEt0_c8pmAqYahfSytLy0e (https://cheerpjdeploy.leaningtech.com/runtime/rt.jar.com.js:2950:3020)
    at Object.func (https://cheerpjdeploy.leaningtech.com/loader.js:468:16)
    at runContinuationStack (https://cheerpjdeploy.leaningtech.com/loader.js:287:10)
    at cheerpjSchedule (https://cheerpjdeploy.leaningtech.com/loader.js:709:4)
    at HTMLScriptElement.classLoadComplete (https://cheerpjdeploy.leaningtech.com/loader.js:177:3)

test-saxon.html?xmlFile=&xsltFile=:1 Failed to load https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://static.adamretter.org.uk' is therefore not allowed access.
```

Can you tell me if I am doing something wrong in the use of Cheerpj or if this is a bug in Cheerpj?
My code is here - http://static.adamretter.org.uk/test-saxon.html

Thanks

**Comment by alexp-sssup** [comment]
There seem to be an issue with passing some primitives JS types to Java functions, we will investigate this.

**Comment by alexp-sssup** [comment]
Beside that, code seems to be initializing properly as messages comes from the Java side on the browser console. For easier debugging you can create a ```<pre>``` in the page with id "console" to see all Java messages.

**Comment by adamretter** [comment]
@alexp-sssup Thanks. I added the `<pre id="console"/>`, but it did not provide any more information that what I had from Chrome Developer Tools Console. 

I look forward to hearing back from you regards the type passing from JS to Java.

**Comment by alexp-sssup** [comment]
Please try again with CheerpJ Beta 2: https://leaningtech.com/cheerpj/download/noncommercial/index.html

**Comment by alexp-sssup** [comment]
@adamretter did youhave a chance to try again with CheerpJ Beta 2?

**Comment by alexp-sssup** [comment]
Closing, this bug is now fixed.
